data_dir: /home/unify/Project/kaggle-child-mind-institute-detect-sleep-states-main/data
processed_dir: /home/unify/Project/kaggle-child-mind-institute-detect-sleep-states-main/processed_data
output_dir: /home/unify/Project/kaggle-child-mind-institute-detect-sleep-states-main/output
model_dir: /home/unify/Project/kaggle-child-mind-institute-detect-sleep-states-main/output/train
sub_dir: /home/unify/Project/kaggle-child-mind-institute-detect-sleep-states-main/sub_dir